import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  en: {
    nav_home: "Home",
    nav_services: "Services",
    nav_about: "About Us",
    nav_contact: "Contact",
    hero_title: "Find Your Dream Property",
    hero_sub: "Premium brokerage services — apartments, commercial spaces, and land plots in Stepanavan and surrounding areas.",
    hero_dubai: "Also advising on Dubai properties",
    hero_cta: "Explore Services",
    hero_cta2: "Contact Us",
    highlights_title: "Our Highlights",
    h1_deals: "1000+ Deals",
    h1_text: "Closed with trust and transparency",
    h2_clients: "98% Satisfaction",
    h2_text: "Long-term relationships with clients",
    h3_years: "3+ Years",
    h3_text: "Deep expertise in real estate",
    ad_here_title: "Here could be your advertisement",
    ad_here_sub: "Promote your brand to engaged property buyers and investors.",
    ad_here_cta: "Contact Us",
    ad_space_available: "Space Available",
    footer_rights: "All rights reserved.",
    footer_desc: "Premium real estate services in Stepanavan and Dubai. Your trusted partner in finding the perfect property.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    // Services
    services_title: "Our Listings",
    filter_all: "All",
    filter_sale: "For Sale",
    filter_rent: "For Rent",
    filter_long: "Long Term",
    prop_beds: "Beds",
    prop_baths: "Baths",
    prop_sqft: "Sq Ft",
    btn_details: "View Details",
    modal_desc: "Description",
    modal_features: "Features",
    modal_call_now: "Contact Agent",
    // About
    about_title: "About VARDANYAN Realty",
    about_intro: "Our agency was founded in 2023 with a new vision and fresh approaches. We aim to combine creativity and professionalism, offering personalized solutions to every client. Our team consists of young but experienced specialists who believe that the right idea can change the result.",
    story_title: "Who we are",
    story_text: "Over the course of three years, we have guided thousands of transactions—from first apartments to major commercial acquisitions.",
    values_title: "What we stand for",
    val_1: "Integrity in every interaction",
    val_2: "Transparent, data‑backed advice",
    val_3: "Relentless client advocacy",
    val_4: "Innovation in solutions",
    dubai_title: "Dubai Investments",
    dubai_text: "From beachfront residences to premium commercial assets — we provide end‑to‑end guidance for Dubai’s dynamic market.",
    // Contact
    contact_title: "Contact Us",
    contact_phone: "Phone",
    contact_email: "Email",
    contact_address: "Address",
    address_value: "Garegin Njdeh 27/2 Stepanavan",
    contact_follow: "Follow Us",
    contact_whatsapp: "WhatsApp",
    contact_viber: "Viber",
    footer_contacts: "Contacts",
    footer_follow: "Follow"
  },
  ru: {
    nav_home: "Главная",
    nav_services: "Услуги",
    nav_about: "О Нас",
    nav_contact: "Контакты",
    hero_title: "Найдите недвижимость мечты",
    hero_sub: "Премиальные брокерские услуги — квартиры, коммерческие помещения и земельные участки в Степанаване и окрестностях.",
    hero_dubai: "Консультации по недвижимости в Дубае",
    hero_cta: "Наши Услуги",
    hero_cta2: "Связаться",
    highlights_title: "Наши Преимущества",
    h1_deals: "1000+ Сделок",
    h1_text: "Закрыто с доверием и прозрачностью",
    h2_clients: "98% Довольных",
    h2_text: "Долгосрочные отношения с клиентами",
    h3_years: "3+ Года",
    h3_text: "Глубокая экспертиза в недвижимости",
    ad_here_title: "Здесь может быть ваша реклама",
    ad_here_sub: "Продвигайте свой бренд среди покупателей и инвесторов.",
    ad_here_cta: "Связаться",
    ad_space_available: "Рекламное место",
    footer_rights: "Все права защищены.",
    footer_desc: "Премиальные услуги недвижимости в Степанаване и Дубае. Ваш надежный партнер в поиске идеальной недвижимости.",
    footer_privacy: "Политика конфиденциальности",
    footer_terms: "Условия использования",
    // Services
    services_title: "Наши Предложения",
    filter_all: "Все",
    filter_sale: "Продажа",
    filter_rent: "Аренда",
    filter_long: "Долгосрочно",
    prop_beds: "Спальни",
    prop_baths: "Ванные",
    prop_sqft: "Площадь",
    btn_details: "Подробнее",
    modal_desc: "Описание",
    modal_features: "Характеристики",
    modal_call_now: "Связаться с агентом",
    // About
    about_title: "О компании VARDANYAN Realty",
    about_intro: "Наше агентство было основано в 2023 году с новым видением и свежими подходами. Мы стремимся сочетать креативность и профессионализм, предлагая каждому клиенту индивидуальные решения. Наша команда состоит из молодых, но уже опытных специалистов, которые верят, что правильная идея может изменить результат.",
    story_title: "Кто мы",
    story_text: "За более чем три года мы сопроводили тысячи сделок — от первых квартир до крупных коммерческих приобретений.",
    values_title: "Наши принципы",
    val_1: "Честность в каждом взаимодействии",
    val_2: "Прозрачные советы, основанные на данных",
    val_3: "Неустанная защита интересов клиентов",
    val_4: "Инновационные решения",
    dubai_title: "Инвестиции в Дубай",
    dubai_text: "От резиденций на берегу моря до премиальных коммерческих активов — полное сопровождение на динамичном рынке Дубая.",
    // Contact
    contact_title: "Связаться с нами",
    contact_phone: "Телефон",
    contact_email: "Email",
    contact_address: "Адрес",
    address_value: "ул. Гарегина Нжде 27/2, Степанаван",
    contact_follow: "Подписаться",
    contact_whatsapp: "WhatsApp",
    contact_viber: "Viber",
    footer_contacts: "Контакты",
    footer_follow: "Соцсети"
  },
  hy: {
    nav_home: "Գլխավոր",
    nav_services: "Ծառայություններ",
    nav_about: "Մեր Մասին",
    nav_contact: "Կապ",
    hero_title: "Գտեք ձեր երազանքի անշարժ գույքը",
    hero_sub: "Պրեմիում բրոքերային ծառայություններ — բնակարաններ, կոմերցիոն տարածքներ և հողատարածքներ Ստեփանավանում:",
    hero_dubai: "Խորհրդատվություն Դուբայի անշարժ գույքի վերաբերյալ",
    hero_cta: "Ծառայություններ",
    hero_cta2: "Կապվել Մեզ Հետ",
    highlights_title: "Մեր Առավելությունները",
    h1_deals: "1000+ Գործարք",
    h1_text: "Իրականացվել է վստահությամբ և թափանցիկությամբ",
    h2_clients: "98% Գոհունակություն",
    h2_text: "Երկարաժամկետ հարաբերություններ հաճախորդների հետ",
    h3_years: "3+ Տարի",
    h3_text: "Խորը փորձ անշարժ գույքի ոլորտում",
    ad_here_title: "Այստեղ կարող է լինել ձեր գովազդը",
    ad_here_sub: "Խթանեք ձեր ապրանքանիշը գնորդների և ներդրողների շրջանում:",
    ad_here_cta: "Կապվել",
    ad_space_available: "Գովազդային տարածք",
    footer_rights: "Բոլոր իրավունքները պաշտպանված են:",
    footer_desc: "Պրեմիում անշարժ գույքի ծառայություններ Ստեփանավանում և Դուբայում։ Ձեր վստահելի գործընկերը կատարյալ գույք գտնելու գործում։",
    footer_privacy: "Գաղտնիության քաղաքականություն",
    footer_terms: "Օգտագործման պայմաններ",
    // Services
    services_title: "Մեր Առաջարկները",
    filter_all: "Բոլորը",
    filter_sale: "Վաճառք",
    filter_rent: "Օրավարձ",
    filter_long: "Երկարաժամկետ",
    prop_beds: "Ննջասենյակ",
    prop_baths: "Սանհանգույց",
    prop_sqft: "Մակերես",
    btn_details: "Մանրամասն",
    modal_desc: "Նկարագրություն",
    modal_features: "Առանձնահատկություններ",
    modal_call_now: "Կապվել գործակալի հետ",
    // About
    about_title: "Մեր գործակալության մասին",
    about_intro: "Մեր գործակալությունը հիմնադրվել է 2023 թվականին՝ նոր տեսլականով և թարմ մոտեցումներով։ Մենք նպատակ ունենք համատեղել ստեղծարարությունը և պրոֆեսիոնալիզմը՝ յուրաքանչյուր հաճախորդին առաջարկելով անհատականացված լուծումներ։ Մեր թիմը բաղկացած է երիտասարդ, բայց արդեն փորձառու մասնագետներից, ովքեր հավատում են, որ ճիշտ գաղափարը կարող է փոխել արդյունքը։",
    story_title: "Մեր պատմությունը",
    story_text: "Ավելի քան երեք տարվա ընթացքում ուղեկցել ենք հազարավոր գործարքներ՝ առաջին բնակարանից մինչև խոշոր կոմերցիոն ձեռքբերումներ։",
    values_title: "Մեր արժեքները",
    val_1: "Ազնվություն յուրաքանչյուր գործարքում",
    val_2: "Թափանցիկ, տվյալների վրա հիմնված խորհուրդներ",
    val_3: "Հաճախորդների շահերի անխոնջ պաշտպանություն",
    val_4: "Նորարարական լուծումներ",
    dubai_title: "Ներդրումներ Դուբայում",
    dubai_text: "Ծովափնյա բնակարաններից մինչև պրեմիում կոմերցիոն ակտիվներ — ամբողջական ուղեցույց Դուբայի դինամիկ շուկայի համար:",
    // Contact
    contact_title: "Կապ Մեզ Հետ",
    contact_phone: "Հեռախոս",
    contact_email: "Էլ. հասցե",
    contact_address: "Հասցե",
    address_value: "Գարեգին Նժդեհի 27/2, Ստեփանավան",
    contact_follow: "Հետևեք Մեզ",
    contact_whatsapp: "WhatsApp",
    contact_viber: "Viber",
    footer_contacts: "Կոնտակտներ",
    footer_follow: "Սոցցանցեր"
  }
};